# Generated by Django 2.2.5 on 2019-09-11 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('FirstApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wish',
            old_name='body',
            new_name='mywish',
        ),
        migrations.RenameField(
            model_name='wish',
            old_name='title',
            new_name='wishtitle',
        ),
    ]
